export enum CancelEventReason {
  CHANGE_EVENT = 'CHANGE_EVENT',
  HAVE_WORK_TODO = 'HAVE_WORK_TODO',
  FULL_PARTICIPANT = 'FULL_PARTICIPANT',
  DONT_WANT_TODO = 'DONT_WANT_TODO',
  OTHER = 'OTHER',
}
